### ISSUE TITLE
Throwing general error.

### ISSUE THREAD

**Issue by Kneesox** [interfect/cjdns-installer#14]
1503903298 INFO cjdroute2.c:641 Cjdns i386 win32
1503903298 INFO cjdroute2.c:645 Checking for running instance...
1503903298 DEBUG UDPAddrIface.c:293 Bound to address [0.0.0.0:58940]
1503903298 DEBUG AdminClient.c:333 Connecting to [127.0.0.1:11234]
1503903300 DEBUG Pipe.c:134 Buffering a message
1503903300 DEBUG cjdroute2.c:698 Sent [140] bytes to core
1503903300 INFO RandomSeed.c:42 Attempting to seed random number generator
1503903300 INFO RandomSeed.c:50 Trying random seed [RtlGenRandom() (Windows)] Su
ccess
1503903300 INFO RandomSeed.c:64 Seeding random number generator succeeded with [
1] sources
1503903300 INFO LibuvEntropyProvider.c:59 Taking clock samples every [1000]ms fo
r random generator
1503903300 DEBUG 1C503903300 DEBUG ore.cP:ipe.c354 :G231 etting pre-configuratio
n from client
P1ipe [\\.\pipe\cjdns_pipe_client-core-f5s3rur3r6whwv7n5frgnd77m5ujwx] established connection
503903300 DEBUG 1P503903300 DEBUG ipe.cP:ipe.c231 :P253 ipe [\\.\pipe\cjdns_pipe_client-core-f5s3rur3r6whwv7n5frgnd77m5ujwx] established connection
Sending buffered message
1503903300 DEBUG Core.c:357 Finished getting pre-configuration from client
1503903300 DEBUG UDPAddrIface.c:254 Binding to address [127.0.0.1:11234]
1503903300 DEBUG UDPAddrIface.c:293 Bound to address [127.0.0.1:11234]
1503903300 DEBUG UDPAddrIface.c:293 Bound to address [0.0.0.0:62892]
1503903300 DEBUG AdminClient.c:333 Connecting to [127.0.0.1:11234]
1503903300 INFO Configurator.c:135 Checking authorized password 0.
1503903300 INFO Configurator.c:159 Adding authorized password #[0] for user [def
ault-login].
1503903300 WARN Configurator.c:111 Got error [Failed to configure tunnel [WinFail.c:3059 CreateUnicastIpAddressEntry(&ipRow) [ERROR_NOT_FOUND]]] calling [Core_initTunnel], ignoring.
1503903300 DEBUG Configurator.c:524 Security_chroot(/var/run/)
1503903300 DEBUG Configurator.c:569 Security_noforks()
1503903300 DEBUG Configurator.c:589 Security_seccomp()
1503903300 DEBUG Configurator.c:594 Security_setupComplete()
1503903300 DEBUG Configurator.c:678 Cjdns started in the background
1503903300 DEBUG cjdroute2.c:739 Keeping cjdns client alive because --nobg was specified on the command line

**Comment by interfect** [comment]
Does cjdns work despite complaining it encountered an error? The message says cjdns is ignoring the error from Windows, so maybe the cjdns code expects to get this error under some circumstances.

If cjdns is not working, exactly how is it not working? Do you not see a meshnet IP in `ipcoinfig /all`? Are you unable to communicate with other meshnet nodes through cjdns? Are you trying to do IpTunnel and having that not work for you?
