### ISSUE TITLE
Service fails to start on Windows 10 

### ISSUE THREAD

**Issue by cschmittiey** [interfect/cjdns-installer#2]
When trying to start cjdns, I get this error: "Error 1053: The service did not respond to the start or control request in a timely fashion."

**Comment by cschmittiey** [comment]
By the way, I'm on the latest build, 9926. On previous builds, it worked fine.

**Comment by interfect** [comment]
That's a bit difficult to debug, and I haven't got a Windows 10 handy to
test on.

Are you sure you have .NET set up right?

Has something changed about services and file permissions?

Is there a cjdroute.conf in the same directory as the service .exe?

If none of that is the problem, I think I can make you an exe that doesn't
run as a service (following <
http://www.codeproject.com/Articles/10153/Debugging-Windows-Services-under-Visual-Studio-NET>,
and you can maybe get some more interesting exception info.

**Comment by cschmittiey** [comment]
Tried reinstalling, works now. Sorry to bother you.
