### ISSUE TITLE
Initial configuration doesn't work

### ISSUE THREAD

**Issue by kaotisk-hund** [interfect/cjdns-installer#24]
In the generated config that ships with cjdns-installer, all the connections are getting to the IPv4 section.

There are also a lot nodes with too much information (known bug) in their blocks as well as others no connections since 2015.

**Comment by andrasfuchs** [comment]
I think the configuration file problem must be related to the issue that [cjdns](https://github.com/cjdelisle/cjdns) has: running the `cjdroute --genconf >> cjdroute.conf` command will produce an invalid file. To fix it, the line #117 must be removed from the `cjdroute.conf` file that is installed into the `c:\Program Files (x86)\cjdns\` folder by default. 
![image](https://user-images.githubusercontent.com/910321/167479072-c2feb2ef-6f84-4d6a-b920-fde06efe4939.png)
We can't do more about it until they do a fix in [the original cjdns repo](https://github.com/cjdelisle/cjdns).

Does having too many peers in our config file cause problems for cjdns? My understanding is that we need them only for the initialization phase and they will be updated/removed as soon as we find valid peers. I added a few more recent peers from [Hyperbolia peers repo](https://github.com/hyperboria/peers), but they might be already out of date. [fc00](https://www.fc00.org) seems to be down too. 
I agree that the no longer working peers should be removed from [public_peers.txt](https://github.com/interfect/cjdns-installer/blob/master/installation/public_peers.txt).

**Comment by kaotisk-hund** [comment]
About the "too many peers". I think there is no problem with the amount of them. They problem from peering information is that when we mention a connection, cjdns waits an "up to number" bytes. Important information is:
- login ( if not default )
- password
- publickey
- peerName (optional)
the rest is either way ignored or choking cjdns configuration file. However, if cjdns receives more bytes can lead to problems. Sorry I don't have an issue link or a point to show to. I know this by testing and discussion over irc.

**Comment by kaotisk-hund** [comment]
I am over testing which ones are working and preparing a first stage patch over the same file.
I will then introduce a "pubic_peers_6.txt" file moving the IPv6 peers there.

**Comment by kaotisk-hund** [comment]
> We can't do more about it until they do a fix in the original cjdns repo.

which version do we have? 21.1.6 seems to have no issue with that.

**Comment by andrasfuchs** [comment]
Great, thank you!

I think we need to modify the [addPublicPeers.vbs](https://github.com/interfect/cjdns-installer/blob/master/installation/addPublicPeers.vbs) and [installer.nsi](https://github.com/interfect/cjdns-installer/blob/master/installer.nsi) files to add the ipv6 peers from the new [public_peers_6.txt](https://github.com/interfect/cjdns-installer/pull/26/files#diff-7067eefc1b6db534b3557a93caa3da136630bd3a37a63c1c5d4f73ecc920c841).
Also, if we have them in separate files, it would make sence to name them `public_peers_ipv4.txt` and `public_peers_ipv6.txt`, I think.

We have [cjdns v21.2](https://github.com/cjdelisle/cjdns/releases/tag/cjdns-v21.2) at the moment. Do you think we should roll back to [v21.1](https://github.com/cjdelisle/cjdns/releases/tag/cjdns-v21.1)?

**Comment by kaotisk-hund** [comment]
I think it 's finally ready. I can't test it now, cause I can't build it :(

Also, sorry for not answering about the roll back. For development it's not that of an issue, for shipping a binary installer ready to go, I think either a roll back or a surgical removal would be enough.
