### ISSUE TITLE
cjdroute.exe from official cjdns github repo throws error

### ISSUE THREAD

**Issue by satindergrewal** [interfect/cjdns-installer#5]
When using cjdroute.exe from `https://github.com/interfect/cjdns-installer` the cjdroute.exe process keeps stable and does not break. The ouput of cjdroute.exe from `interfect` is as follows:

`C:\Users\Sat\Downloads\cjdns>cjdroute.exe --nobg < cjdroute.conf`
`1446105450 INFO cjdroute2.c:585 Cjdns i386 win32`
`1446105450 INFO cjdroute2.c:589 Checking for running instance...`
`1446105450 DEBUG UDPAddrIface.c:294 Bound to address [0.0.0.0:51778]`
`1446105450 DEBUG AdminClient.c:333 Connecting to [127.0.0.1:11234]`
`1446105450 DEBUG Pipe.c:134 Buffering a message`
`1446105450 DEBUG cjdroute2.c:634 Sent [140] bytes to core`
`1446105450 INFO RandomSeed.c:42 Attempting to seed random number generator`
`1446105450 INFO RandomSeed.c:50 Trying random seed [RtlGenRandom() (Windows)] Success`
`1446105450 INFO RandomSeed.c:64 Seeding random number generator succeeded with [1] sources`
`1446105450 INFO LibuvEntropyProvider.c:59 Taking clock samples every [1000]ms for random generator`
`1446105450 DEBUG Core.c:256 Getting pre-configuration from client`
`1446105450 DEBUG Pipe.c1446105450 DEBUG Pipe.c:231 Pipe [\\.\pipe\cjdns_pipe_client-core-m447gg6xvtw0ryg8uwyrs3pph7nrus] established connection`
`1:231 Pipe [\\.\pipe\cjdns_pipe_client-core-m447gg6xvtw0ryg8uwyrs3pph7nrus] established connection`
`446105450 DEBUG Pipe.c:253 Sending buffered message`
`1446105450 DEBUG Core.c:259 Finished getting pre-configuration from client`
`1446105450 DEBUG UDPAddrIface.c:255 Binding to address [127.0.0.1:11234]`
`1446105450 DEBUG UDPAddrIface.c:294 Bound to address [127.0.0.1:11234]`
`1446105450 DEBUG UDPAddrIface.c:294 Bound to address [0.0.0.0:51779]`
`1446105450 DEBUG AdminClient.c:333 Connecting to [127.0.0.1:11234]`
`1446105450 INFO Configurator.c:135 Checking authorized password 0.`
`1446105450 INFO Configurator.c:157 Adding authorized password #[0] for user [password [0]].`
`Ok.`

`1446105451 DEBUG Configurator.c:486 Security_chroot(/var/run/)`
`1446105451 DEBUG Configurator.c:529 Security_noforks()`
`1446105451 DEBUG Configurator.c:546 Security_seccomp()`
`1446105451 DEBUG Configurator.c:551 Security_setupComplete()`
`1446105451 DEBUG Configurator.c:635 Cjdns started in the background`
`1446105451 DEBUG cjdroute2.c:675 Keeping cjdns client alive because --nobg was specified on the command line`
`^C`

But, when using cjdroute.exe cross compiled from latest cjdns repository on ubuntu 15.04 using the instructions mentioned here `https://docs.meshwith.me/install/windows.html`, when executing cjdroute.exe it starts, but throws error when trying connecting to other cjdns node, either sending ping request, or opening the service through web browser (using IPv6 and dns):

`C:\Users\Sat\Downloads\cjdns>cjdroute0.exe --nobg < cjdroute.conf`
`1446105708 INFO cjdroute2.c:585 Cjdns i386 win32`
`1446105708 INFO cjdroute2.c:589 Checking for running instance...`
`1446105708 DEBUG UDPAddrIface.c:294 Bound to address [0.0.0.0:55083]`
`1446105708 DEBUG AdminClient.c:333 Connecting to [127.0.0.1:11234]`
`1446105708 DEBUG Pipe.c:134 Buffering a message`
`1446105708 DEBUG cjdroute2.c:634 Sent [140] bytes to core`
`1446105708 INFO RandomSeed.c:42 Attempting to seed random number generator`
`1446105708 INFO RandomSeed.c:50 Trying random seed [RtlGenRandom() (Windows)] Success`
`1446105708 INFO RandomSeed.c:64 Seeding random number generator succeeded with [1] sources`
`1446105708 INFO LibuvEntropyProvider.c:59 Taking clock samples every [1000]ms for random generator`
`11446105708 DEBUG 446105708 DEBUG Pipe.cC:231 ore.cPipe [\\.\pipe\cjdns_pipe_client-core-wd6ykufv0526434wncps3lbsc3w08u] established connection`
`:1446105708 DEBUG 256 Pipe.cG:etting pre-configuration from client`
`253 1S446105708 DEBUG ending buffered message`
`Pipe.c:231 Pipe [\\.\pipe\cjdns_pipe_client-core-wd6ykufv0526434wncps3lbsc3w08u] established connection`
`1446105708 DEBUG Core.c:259 Finished getting pre-configuration from client`
`1446105708 DEBUG UDPAddrIface.c:255 Binding to address [127.0.0.1:11234]`
`1446105708 DEBUG UDPAddrIface.c:294 Bound to address [127.0.0.1:11234]`
`1446105708 DEBUG UDPAddrIface.c:294 Bound to address [0.0.0.0:55084]`
`1446105708 DEBUG AdminClient.c:333 Connecting to [127.0.0.1:11234]`
`1446105708 INFO Configurator.c:135 Checking authorized password 0.`
`1446105708 INFO Configurator.c:157 Adding authorized password #[0] for user [password [0]].`
`Ok.`
`
`1446105708 DEBUG Configurator.c:486 Security_chroot(/var/run/)`
`1446105708 DEBUG Configurator.c:529 Security_noforks()`
`1446105708 DEBUG Configurator.c:546 Security_seccomp()`
`1446105708 DEBUG Configurator.c:551 Security_setupComplete()`
`1446105708 DEBUG Configurator.c:635 Cjdns started in the background`
`1446105708 DEBUG cjdroute2.c:675 Keeping cjdns client alive because --nobg was specified on the command line`
`
`
`Assertion failure [NDPServer.c:79] [(!msg->length)]`
`
`This application has requested the Runtime to terminate it in an unusual way.`
`Please contact the application's support team for more information.`
`
`
`Core exited with status [3], signal [0]`
``
`This application has requested the Runtime to terminate it in an unusual way.`
`Please contact the application's support team for more information.`

In both cases when check if the peers are connected through `C:\Users\Sat\Downloads\cjdns\tools>node peerStats` the peers stats ESTABLISHED connection.

Please help resolve issue with the compiled build from the latest cjdns repo.

**Comment by satindergrewal** [comment]
Seems the issue solved. I used Crashey branch of cjdns and that build works fine on winodws. :)

**Comment by interfect** [comment]
Yeah, there's a patch I submitted to fix that. It's in my build, and in
crashey, but not yet in master.

**Comment by interfect** [comment]
I believe that all my patches are in cjdns master now.
